apiVersion: v1
kind: Pod
metadata:
  name: multicontainer
spec:
    containers:
    - name: nginx
      image: nginx:1.20
      ports:
      - containerPort: 80
      command: ['sh','-c']
      args:
      - while true;
          do echo "$(date) INFO some app data" >> /var/log/myapp.log;
          sleep 5;
        done
      volumeMounts:
      - mountPath: /var/log
        name: log-data

    - name: log-sidecar
      image: busybox:1.28
      command: ['sh','-c']
      args:
      - tail -f /var/sidecar/myapp.log
      volumeMounts:
      - mountPath: /var/sidecar
        name: log-data

    volumes:
    - name: log-data
      emptyDir: {}
