apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-db
  labels:
    app: my-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-db
  strategy:
  template:
    metadata:
      labels:
        app: my-db
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: mypwd

        volumeMounts:
        - name: db-data
          mountPath: "/var/lib/mysql"
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: mysql-pvc
